# Generated by Django 5.2.3 on 2026-04-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chargingport_chargingstation_booking_chargingsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingport',
            name='charging_type',
            field=models.CharField(choices=[('Ultra Fast', 'Ultra Fast'), ('Fast', 'Fast'), ('Slow', 'Slow'), ('Standard', 'Standard')], default='Standard', max_length=20),
        ),
    ]
